mockserver:
  endpoint: http://localhost:1080
  api:
    base-path: /api/v1
    create-payments: /payments
    payment-details: /payments/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkout
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none